"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const faqs = [
  {
    question: "How much does Preploy cost?",
    answer:
      "Preploy is free while in beta. You can run as many mock interviews as you like at no charge. Pricing has not been finalized — you will receive notice before any paid tier is introduced.",
  },
  {
    question: "Does Preploy store my audio or transcripts?",
    answer:
      "Your spoken answers are transcribed in real time and the text is stored in your account so you can review feedback later. Raw audio is not retained after transcription. You can delete any session from your dashboard at any time.",
  },
  {
    question: "What interview types are supported?",
    answer:
      "Preploy currently supports behavioral interviews (STAR-format, voice-to-voice with a 3D AI interviewer) and technical interviews (algorithm problems in a code editor, with spoken explanation). More types are planned but not yet live.",
  },
  {
    question: "How accurate is the AI feedback?",
    answer:
      "The feedback is generated by a large language model and scored on a 0–10 scale. It is useful for identifying patterns — filler words, missing context, vague answers — but it is not a human interviewer. Treat it as a structured study partner, not a hiring signal.",
  },
  {
    question: "Can I practice for a specific company or role?",
    answer:
      "Yes. The behavioral setup lets you enter a target company and role, and Preploy tailors the question set accordingly. You can also upload your resume so questions reference your actual experience.",
  },
  {
    question: "How do I get started?",
    answer:
      "Sign in with Google, then click \"Start a free mock interview\" on the home page. You will be prompted to choose behavioral or technical, configure your session, and start speaking. No setup or download required.",
  },
  {
    question: "Is my resume data kept private?",
    answer:
      "Resume content is stored in your account and used only to generate interview questions on your behalf. It is not shared with other users or used to train models.",
  },
];

interface FAQItemProps {
  question: string;
  answer: string;
  isOpen: boolean;
  onToggle: () => void;
}

function FAQItem({ question, answer, isOpen, onToggle }: FAQItemProps) {
  return (
    <div className="border-b last:border-b-0">
      <button
        className="flex w-full items-center justify-between py-4 text-left text-sm font-medium hover:text-primary transition-colors"
        onClick={onToggle}
        aria-expanded={isOpen}
        data-testid="faq-trigger"
      >
        <span>{question}</span>
        <ChevronDown
          className={cn(
            "h-4 w-4 shrink-0 text-muted-foreground transition-transform duration-200",
            isOpen && "rotate-180"
          )}
        />
      </button>
      <div
        className={cn(
          "overflow-hidden transition-all duration-200",
          isOpen ? "max-h-96 pb-4" : "max-h-0"
        )}
        data-testid="faq-content"
      >
        <p className="text-sm text-muted-foreground leading-relaxed">{answer}</p>
      </div>
    </div>
  );
}

export function LandingFAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-20 px-4 bg-muted/30">
      <div className="max-w-2xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12">
          Frequently asked questions
        </h2>
        <div className="rounded-lg border bg-background px-6" data-testid="faq-accordion">
          {faqs.map((faq, index) => (
            <FAQItem
              key={index}
              question={faq.question}
              answer={faq.answer}
              isOpen={openIndex === index}
              onToggle={() => toggle(index)}
            />
          ))}
        </div>
      </div>
    </section>
  );
}
