{/* DRAFT v1 — written 2026-04-16. Review before launch. Replace with lawyer-drafted or Termly-generated text before collecting real user data or accepting real payments. */}

import type { Metadata } from "next";

// Pure static content — no auth, no DB, no per-user data. Force static
// rendering so it serves from Vercel's edge CDN instead of going through
// a fresh Lambda on every request.
export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Privacy Policy — Preploy",
  description: "How Preploy collects, uses, and protects your data.",
  robots: { index: false, follow: false },
};

export default function PrivacyPage() {
  return (
    <main className="max-w-2xl mx-auto px-4 py-24">
      <p className="text-sm text-muted-foreground mb-2">Last updated: 2026-04-17</p>
      <h1 className="text-3xl font-bold tracking-tight mb-2">Privacy Policy</h1>
      <p className="text-sm text-amber-600 dark:text-amber-400 mb-8 border border-amber-300 dark:border-amber-700 rounded px-3 py-2">
        Draft v1. This policy has not been reviewed by a lawyer. It will be
        replaced with a formally reviewed version before Preploy accepts live
        payments or real user data at scale.
      </p>

      <div className="space-y-8 text-sm leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold mb-3">Who we are</h2>
          <p>
            Preploy is an AI-powered mock interview practice service. When this
            policy says &ldquo;Preploy,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our,&rdquo; it refers to the
            individual operating the service. Questions or requests about your
            data can be sent to{" "}
            <a href="mailto:preploy.dev@gmail.com" className="underline hover:text-foreground">
              preploy.dev@gmail.com
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">What data we collect</h2>
          <p className="mb-3">We only collect data necessary to provide and improve the service.</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Account information</strong> — your name, email, and profile picture, provided by Google OAuth. We do not collect your Google password.</li>
            <li><strong>Interview sessions</strong> — configuration, status, and timestamps of each practice session you run.</li>
            <li><strong>Transcripts</strong> — text transcripts of your spoken answers. Audio chunks are sent to OpenAI for transcription and are <strong>not</strong> retained by us after transcription.</li>
            <li><strong>Code snapshots</strong> — code you write during technical interviews, including edits, runs, and submissions.</li>
            <li><strong>AI feedback</strong> — scores, summaries, strengths, and weaknesses generated by OpenAI based on your transcripts and code.</li>
            <li><strong>STAR stories</strong> — structured behavioral stories you write, along with any AI analysis of them.</li>
            <li><strong>Resumes</strong> — the text content of any resume you upload. The original file is not retained after text extraction.</li>
            <li><strong>Interview plans, saved questions, templates</strong> — company names, roles, target dates, and reusable session configurations.</li>
            <li><strong>Usage counters</strong> — how many practice interviews you have run in the current billing period.</li>
            <li><strong>Billing metadata</strong> — Stripe customer and subscription IDs, current plan, subscription dates. We never store full payment card numbers; Stripe handles all card data.</li>
            <li><strong>Achievements</strong> — badges earned through platform usage.</li>
            <li><strong>Error reports</strong> — if Sentry is configured, anonymized stack traces and request metadata may be sent when the app encounters an unexpected error.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">How we use your data</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>To provide the core service: conducting mock interviews, generating feedback, and displaying your history.</li>
            <li>To enforce usage limits and manage your subscription.</li>
            <li>To diagnose bugs and improve the service.</li>
            <li>To respond to support requests.</li>
          </ul>
          <p className="mt-3">
            We do not sell your data. We do not use your data for advertising.
            We do not use your transcripts or stories to train AI models beyond
            what is described in OpenAI&rsquo;s API data usage policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Third-party processors</h2>
          <p className="mb-3">
            Running the service requires sharing data with the following
            processors. Each has its own privacy policy.
          </p>
          <ul className="list-disc pl-5 space-y-3">
            <li><strong>Supabase</strong> — hosts our PostgreSQL database. All data listed above is stored on Supabase-managed infrastructure.</li>
            <li><strong>Vercel</strong> — hosts the web application, serves pages via CDN, runs serverless functions, and stores application logs. Servers are located in the US (primary region: iad1). Vercel may receive request metadata including your IP address and browser user agent.</li>
            <li><strong>Vercel Web Analytics and Speed Insights</strong> — Vercel&rsquo;s first-party analytics products run on the same platform that hosts the application. Web Analytics records aggregated pageview counts, referrer, anonymized country (derived from IP and not stored), device type, and browser family. Speed Insights records anonymized real-user performance timings (Core Web Vitals: LCP, INP, CLS, FCP, TTFB). Neither product sets tracking cookies nor collects IP addresses, email, or any other personally identifying information. Vercel operates these as data processors on our behalf.</li>
            <li><strong>OpenAI</strong> — receives audio chunks (for transcription), interview questions, and your answers/code for feedback generation. OpenAI&rsquo;s API data usage policy applies; by default, API inputs are not used to train OpenAI models.</li>
            <li><strong>Google</strong> — used solely for sign-in (OAuth 2.0). Google provides your name, email, and profile picture. We do not share your interview data back to Google.</li>
            <li><strong>Stripe</strong> — handles all payment processing for Pro subscriptions. Stripe receives your name, email, and payment method details. Preploy never sees or stores your full card number.</li>
            <li><strong>Sentry</strong> — (optional) receives anonymized error reports and request metadata when the application encounters an unexpected error. Only active if Sentry credentials are configured.</li>
          </ul>
          <p className="mt-3">
            If you are located in the EU or UK: your data is processed in the
            United States by the processors above. The lawful basis for this
            transfer is your consent (by using the service) and our legitimate
            interest in operating it.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Cookies and local storage</h2>
          <p>
            We use a single essential cookie for authentication (your NextAuth
            session). Our analytics processor (Vercel Web Analytics) operates
            in cookie-less, anonymous mode — it does not set any tracking
            cookies. We do not use third-party advertising cookies. Your
            browser may cache static assets we serve; that caching is not
            personalized.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Data retention</h2>
          <p>
            We retain your data for as long as your account is active. If you
            delete your account, all associated personal data is hard-deleted
            from our database within 30 days. Backup snapshots containing
            residual data may persist up to an additional 30 days before being
            overwritten.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Your rights</h2>
          <p className="mb-3">Depending on where you live, you may have the right to:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Access</strong> the personal data we hold about you.</li>
            <li><strong>Correct</strong> inaccurate data (e.g., via your profile page).</li>
            <li><strong>Delete</strong> your account and associated data.</li>
            <li><strong>Export</strong> a copy of your data in a machine-readable format.</li>
            <li><strong>Object</strong> to certain types of processing.</li>
          </ul>
          <p className="mt-3">
            To exercise any of these rights, email{" "}
            <a href="mailto:preploy.dev@gmail.com" className="underline hover:text-foreground">
              preploy.dev@gmail.com
            </a>
            . We will respond within 30 days.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Children&rsquo;s privacy</h2>
          <p>
            Preploy is not directed at children under 13. We do not knowingly
            collect personal information from children under 13. If you believe
            we have collected such information, please contact us and we will
            delete it.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Changes to this policy</h2>
          <p>
            We may update this policy from time to time. Material changes will
            be announced on the service and take effect 14 days after the
            updated policy is posted. Your continued use of the service after
            that date means you accept the revised policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Contact</h2>
          <p>
            For any privacy question, request, or complaint, email{" "}
            <a href="mailto:preploy.dev@gmail.com" className="underline hover:text-foreground">
              preploy.dev@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
